const planetToCountry: Record<string, string> = {
    "tatooine": "samoa",
    "alderaan": "norway",
    "yavin iv": "peru",
    "hoth": "canada",
    "dagobah": "brazil",
    "bespin": "egypt",
    "endor": "new zealand",
    "naboo": "italy",
    "coruscant": "japan",
    "kamino": "iceland",
    "geonosis": "spain",
    "utapau": "mexico",
    "mustafar": "indonesia",
    "kashyyyk": "kenya",
    "polis massa": "finland",
    "mygeeto": "india",
    "felucia": "morocco",
    "cato neimoidia": "greece",
    "saleucami": "chile",
    "stewjon": "netherlands",
    "eriadu": "australia",
    "corellia": "argentina",
    "rodia": "south africa",
    "nal hutta": "germany",
    "dantooine": "portugal",
    "bestine iv": "ireland",
    "ord mantell": "colombia",
    "unknown": "singapore",
    "trandosha": "sweden",
    "socorro": "poland",
    "mon cala": "philippines",
    "chandrila": "thailand",
    "sullust": "vietnam",
    "toydaria": "switzerland",
    "malastare": "austria",
    "dathomir": "belgium",
    "ryloth": "denmark",
    "aleen minor": "czechia",
    "vulpter": "hungary",
    "troiken": "romania",
    "tund": "bulgaria",
    "haruun kal": "croatia",
    "cerea": "serbia",
    "glee anselm": "slovakia",
    "iridonia": "slovenia",
    "tholoth": "estonia",
    "iktotch": "latvia",
    "quermia": "lithuania",
    "dorin": "ukraine",
    "champala": "belarus",
    "mirial": "georgia",
    "serenno": "armenia",
    "concord dawn": "azerbaijan",
    "zolan": "israel",
    "ojom": "jordan",
    "skako": "saudi arabia",
    "muunilinst": "united arab emirates",
    "shili": "qatar",
    "kalee": "oman",
    "umbara": "fiji",
} as const;


export function countryForPlanetName(name: string): string | undefined {
    return planetToCountry[name.trim().toLowerCase()];
}
